import { z } from 'zod';
import { createOpaqueServerFromEnv } from '@hushbox/crypto';
import { normalizeUsername } from '@hushbox/shared';
import { provisionWalletsWithinTx } from '../../billing/index.js';
import { Result, fromPromise, okAsync } from '../../../lib/result/index.js';
import { unavailableError } from '../../../lib/errors/index.js';
import { runSettlement } from '../../../lib/idempotency/index.js';
import { redisGetDel, redisSet } from '../../../lib/redis/index.js';
import { decodeBase64Field } from './guards.js';
import { EMAIL_VERIFY_TOKEN_TTL_MS } from './email-verification.js';
import { IDENTITY_KEYS } from './keys.js';
import { consumeRateLimit } from './rate-limit.js';
import {
  deserializeRegistrationRecord,
  deserializeRegistrationRequest,
  opaqueProtocolError,
  throwIfOpaqueError,
} from './opaque.js';
import type { OpaqueServerRegistrationRequest } from '@hushbox/crypto';
import type { Database } from '@hushbox/db';
import type { BillingStores, WelcomeEmailPort } from '../../billing/index.js';
import type { DomainError } from '../../../lib/errors/index.js';
import type { ResultAsync } from '../../../lib/result/index.js';
import type {
  IdentityUsersStore,
  IdentityVerificationStore,
  InsertRegisteredOutcome,
  RegistrationValues,
  VerificationEmailPort,
} from '../ports/index.js';
import type { OpaqueFinishFlow } from './opaque.js';
import type { RedisClient } from './keys.js';

export const registerInitBodySchema = z.object({
  email: z.email().max(254),
  username: z.string().min(1).max(20),
  registrationRequest: z.array(z.number()).min(1),
});

export const registerFinishBodySchema = z.object({
  email: z.email().max(254),
  registrationRecord: z.array(z.number()).min(1),
  accountPublicKey: z.string().min(1),
  passwordWrappedPrivateKey: z.string().min(1),
  recoveryWrappedPrivateKey: z.string().min(1),
  registerSessionId: z.uuid(),
});

export interface RegistrationStartArgs {
  readonly store: IdentityUsersStore;
  readonly redis: RedisClient;
  readonly masterSecret: string;
  readonly email: string;
  readonly username: string;
  readonly registrationRequest: number[];
  readonly now: number;
}

export type RegistrationStartOutcome =
  | { readonly kind: 'rate-limited'; readonly retryAfterSeconds: number }
  | {
      readonly kind: 'started';
      readonly registrationResponse: number[];
      readonly registerSessionId: string;
    };

/**
 * Round one of OPAQUE registration. The request is processed identically
 * whether or not the email is already registered — the existing flag rides
 * along in the pending state so the finish round can answer the same
 * fake-success shape, preventing account enumeration.
 */
export function startRegistration(
  args: RegistrationStartArgs
): ResultAsync<RegistrationStartOutcome, DomainError> {
  const email = args.email.toLowerCase();
  return consumeRateLimit(args.redis, IDENTITY_KEYS.registerRateLimit, email, args.now).andThen(
    (decision) =>
      decision.allowed
        ? beginRegistrationHandshake(args, email)
        : okAsync<RegistrationStartOutcome, DomainError>({
            kind: 'rate-limited',
            retryAfterSeconds: decision.retryAfterSeconds,
          })
  );
}

function beginRegistrationHandshake(
  args: RegistrationStartArgs,
  email: string
): ResultAsync<RegistrationStartOutcome, DomainError> {
  return deserializeRegistrationRequest(args.registrationRequest)
    .asyncAndThen((request) => prepareRegistration(args, email, request))
    .andThen((prepared) => storePendingRegistration(args, email, prepared));
}

interface PreparedRegistration {
  readonly serializedResponse: number[];
  readonly existing: boolean;
  readonly userId: string;
}

function prepareRegistration(
  args: RegistrationStartArgs,
  email: string,
  request: OpaqueServerRegistrationRequest
): ResultAsync<PreparedRegistration, DomainError> {
  return args.store
    .findByEmail(email)
    .andThen((existingUser) => runRegisterInit(args, request, existingUser !== null));
}

/**
 * Mints the durable `users.id` as a UUIDv7 — a 48-bit big-endian millisecond
 * timestamp prefix followed by a random tail — so the most-joined table keeps
 * B-tree insert locality and time-ordering (parity with every other PK, which
 * uses the schema's DB-side `uuidv7()`).
 *
 * It is minted app-side rather than deferred to the `users.id` column default
 * because this same value is the OPAQUE `credential_identifier`: it is bound in
 * `registerInit` BEFORE the row exists and re-supplied verbatim at login
 * (`authInit`) to seed the per-user OPRF key. The two calls must pass a
 * byte-identical identifier, and login can only rebind on `users.id` (it accepts
 * either username or email as the submitted identifier), so the id cannot be
 * generated by the INSERT — it must be known at register-init.
 */
export function generateUserId(now: number): string {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  const view = new DataView(bytes.buffer);
  const ts = BigInt(Math.trunc(now));
  for (let index = 0; index < 6; index += 1) {
    view.setUint8(index, Number((ts >> BigInt((5 - index) * 8)) & 0xffn));
  }
  view.setUint8(6, (view.getUint8(6) & 0x0f) | 0x70); // version 7
  view.setUint8(8, (view.getUint8(8) & 0x3f) | 0x80); // RFC 4122 variant
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0'));
  return `${hex.slice(0, 4).join('')}-${hex.slice(4, 6).join('')}-${hex.slice(6, 8).join('')}-${hex.slice(8, 10).join('')}-${hex.slice(10, 16).join('')}`;
}

function runRegisterInit(
  args: RegistrationStartArgs,
  request: OpaqueServerRegistrationRequest,
  existing: boolean
): ResultAsync<PreparedRegistration, DomainError> {
  const userId = generateUserId(args.now);
  return fromPromise(
    (async (): Promise<PreparedRegistration> => {
      const server = await createOpaqueServerFromEnv(args.masterSecret);
      const response = throwIfOpaqueError(await server.registerInit(request, userId));
      return { serializedResponse: response.serialize(), existing, userId };
    })(),
    opaqueProtocolError('OPAQUE registerInit rejected the request')
  );
}

function storePendingRegistration(
  args: RegistrationStartArgs,
  email: string,
  prepared: PreparedRegistration
): ResultAsync<RegistrationStartOutcome, DomainError> {
  const registerSessionId = crypto.randomUUID();
  return redisSet(
    args.redis,
    IDENTITY_KEYS.opaquePendingRegistration,
    {
      email,
      username: normalizeUsername(args.username),
      userId: prepared.userId,
      ...(prepared.existing ? { existing: true } : {}),
    },
    registerSessionId
  ).map(
    (): RegistrationStartOutcome => ({
      kind: 'started',
      registrationResponse: prepared.serializedResponse,
      registerSessionId,
    })
  );
}

export type ConsumePendingRegistrationOutcome =
  | { readonly kind: 'no-pending' }
  | { readonly kind: 'existing' }
  | {
      readonly kind: 'pending';
      readonly userId: string;
      readonly email: string;
      readonly username: string;
    };

/**
 * Resolves and CONSUMES the pending registration state in one atomic Redis
 * GETDEL — strictly single-use. The read and delete are a single operation,
 * so two concurrent finish deliveries (or a crash-retry) can never both
 * observe the state: exactly one wins it and the other reads null, taking the
 * no-pending path. This is the `opaque-protocol` finish route's atomic
 * first-delivery claim on the handshake id — a GET-then-DEL pair would let
 * both deliveries win and race the account INSERT.
 */
export function consumePendingRegistration(args: {
  readonly redis: RedisClient;
  readonly email: string;
  readonly registerSessionId: string;
}): ResultAsync<ConsumePendingRegistrationOutcome, DomainError> {
  return redisGetDel(
    args.redis,
    IDENTITY_KEYS.opaquePendingRegistration,
    args.registerSessionId
  ).map((pending): ConsumePendingRegistrationOutcome => {
    if (pending === null) return { kind: 'no-pending' };
    // Defense-in-depth: a stolen handshake id must not complete a
    // registration for a different email.
    if (pending.email !== args.email.toLowerCase()) return { kind: 'no-pending' };
    if (pending.existing === true) return { kind: 'existing' };
    return {
      kind: 'pending',
      userId: pending.userId,
      email: pending.email,
      username: pending.username,
    };
  });
}

export interface CompleteRegistrationArgs {
  readonly db: Database;
  readonly store: IdentityUsersStore;
  readonly billingStores: BillingStores;
  readonly verificationStore: IdentityVerificationStore;
  readonly welcomeEmail: WelcomeEmailPort;
  readonly verificationEmail: VerificationEmailPort;
  readonly pending: { readonly userId: string; readonly email: string; readonly username: string };
  readonly registrationRecord: number[];
  readonly accountPublicKey: string;
  readonly passwordWrappedPrivateKey: string;
  readonly recoveryWrappedPrivateKey: string;
  readonly now: number;
}

/**
 * The account INSERT plus wallet + welcome-credit provisioning, preceded by
 * pure input decoding. Insert and provisioning commit in ONE settlement
 * transaction (§8 single-settlement): a crash between them leaves neither, so
 * a registered user always owns the wallets `requirePurchasedWallet` demands —
 * there is no lazy re-provision path. A racing duplicate resolves to
 * `email-taken` / `username-taken` as a value (the INSERT does no work) and
 * provisioning is skipped. On success, best-effort notifications fire outside
 * the transaction: the welcome email (unconditionally — the greeting is
 * decoupled from whether a promo credit was granted) and the verification
 * token + email — neither can block or fail the 201.
 */
export function completeRegistration(
  args: CompleteRegistrationArgs
): ResultAsync<InsertRegisteredOutcome, DomainError> {
  return decodeRegistrationValues(args).asyncAndThen((values) =>
    finalizeRegistration(args, values)
  );
}

function decodeRegistrationValues(
  args: CompleteRegistrationArgs
): Result<RegistrationValues, DomainError> {
  return deserializeRegistrationRecord(args.registrationRecord).andThen((record) =>
    Result.combine([
      decodeBase64Field(args.accountPublicKey, 'accountPublicKey'),
      decodeBase64Field(args.passwordWrappedPrivateKey, 'passwordWrappedPrivateKey'),
      decodeBase64Field(args.recoveryWrappedPrivateKey, 'recoveryWrappedPrivateKey'),
    ]).map(
      ([publicKey, passwordWrappedPrivateKey, recoveryWrappedPrivateKey]): RegistrationValues => ({
        id: args.pending.userId,
        email: args.pending.email,
        username: args.pending.username,
        opaqueRegistration: new Uint8Array(record.serialize()),
        publicKey,
        passwordWrappedPrivateKey,
        recoveryWrappedPrivateKey,
      })
    )
  );
}

function finalizeRegistration(
  args: CompleteRegistrationArgs,
  values: RegistrationValues
): ResultAsync<InsertRegisteredOutcome, DomainError> {
  return fromPromise(runRegistrationSettlement(args, values), (cause) =>
    unavailableError('registration settlement failed', cause)
  ).andThen((outcome) =>
    outcome.kind === 'created'
      ? dispatchRegistrationSideEffects(args).map((): InsertRegisteredOutcome => outcome)
      : okAsync<InsertRegisteredOutcome, DomainError>(outcome)
  );
}

/**
 * Insert then provision, atomically. Provisioning is skipped when the INSERT
 * hit a unique violation — nothing was written, so the transaction commits
 * empty and the caller surfaces the taken outcome.
 */
async function runRegistrationSettlement(
  args: CompleteRegistrationArgs,
  values: RegistrationValues
): Promise<InsertRegisteredOutcome> {
  return runSettlement(args.db, async (tx) => {
    const outcome = await args.store.insertRegisteredWithinTx(tx, values);
    if (outcome.kind === 'created') {
      await provisionWalletsWithinTx(args.billingStores, tx, outcome.userId);
    }
    return outcome;
  });
}

/**
 * Best-effort post-commit notifications for a newly created account: the
 * welcome greeting (always sent — decoupled from promo-credit grant) and the
 * verification token + email. Neither can block or fail the 201.
 */
export function dispatchRegistrationSideEffects(
  args: CompleteRegistrationArgs
): ResultAsync<void, DomainError> {
  const to = args.pending.email;
  const userName = args.pending.username;
  return args.welcomeEmail
    .sendWelcomeEmail({ to, userName })
    .orElse(() => okAsync())
    .andThen(() => issueVerification(args, to, userName));
}

/**
 * Issues a fresh single-use verification token and sends the link, all
 * best-effort: a token-issue or send failure is swallowed so registration
 * still returns 201 (the user can re-request via the resend route).
 */
function issueVerification(
  args: CompleteRegistrationArgs,
  to: string,
  userName: string
): ResultAsync<void, DomainError> {
  const token = crypto.randomUUID();
  const expiresAt = new Date(args.now + EMAIL_VERIFY_TOKEN_TTL_MS);
  return args.verificationStore
    .issueEmailVerification(args.pending.userId, token, expiresAt)
    .andThen(() => args.verificationEmail.sendVerificationEmail({ to, token, userName }))
    .orElse(() => okAsync());
}

export type RegisterFinishOutcome =
  | { readonly kind: 'no-pending' }
  | { readonly kind: 'existing' }
  | InsertRegisteredOutcome;

export interface RegisterFinishFlowArgs {
  readonly store: IdentityUsersStore;
  readonly redis: RedisClient;
  readonly db: Database;
  readonly billingStores: BillingStores;
  readonly verificationStore: IdentityVerificationStore;
  readonly welcomeEmail: WelcomeEmailPort;
  readonly verificationEmail: VerificationEmailPort;
  readonly email: string;
  readonly registerSessionId: string;
  readonly registrationRecord: number[];
  readonly accountPublicKey: string;
  readonly passwordWrappedPrivateKey: string;
  readonly recoveryWrappedPrivateKey: string;
  readonly now: number;
}

/**
 * The register-finish `byEventId` composition (see `OpaqueFinishFlow`):
 * consuming the pending handshake is the first-delivery claim — a replayed
 * finish finds nothing and takes the duplicate path.
 */
export function createRegisterFinishFlow(
  args: RegisterFinishFlowArgs
): OpaqueFinishFlow<RegisterFinishOutcome> {
  let consumed: ConsumePendingRegistrationOutcome = { kind: 'no-pending' };
  return {
    claim: () =>
      consumePendingRegistration({
        redis: args.redis,
        email: args.email,
        registerSessionId: args.registerSessionId,
      }).map((outcome) => {
        consumed = outcome;
        return outcome.kind !== 'no-pending';
      }),
    execute: () => executeRegisterFinish(args, consumed),
    onDuplicate: () => okAsync<RegisterFinishOutcome, DomainError>({ kind: 'no-pending' }),
  };
}

function executeRegisterFinish(
  args: RegisterFinishFlowArgs,
  consumed: ConsumePendingRegistrationOutcome
): ResultAsync<RegisterFinishOutcome, DomainError> {
  if (consumed.kind === 'no-pending') {
    // `execute` runs only for the delivery that won the claim; a
    // no-pending consume can never win it.
    throw new Error('identity: register finish executed without a claimed pending state');
  }
  if (consumed.kind === 'existing') {
    return okAsync<RegisterFinishOutcome, DomainError>({ kind: 'existing' });
  }
  return completeRegistration({
    db: args.db,
    store: args.store,
    billingStores: args.billingStores,
    verificationStore: args.verificationStore,
    welcomeEmail: args.welcomeEmail,
    verificationEmail: args.verificationEmail,
    pending: consumed,
    registrationRecord: args.registrationRecord,
    accountPublicKey: args.accountPublicKey,
    passwordWrappedPrivateKey: args.passwordWrappedPrivateKey,
    recoveryWrappedPrivateKey: args.recoveryWrappedPrivateKey,
    now: args.now,
  });
}
