/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as Customer360RouteImport } from './routes/customer-360'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer360Route = Customer360RouteImport.update({
  id: '/customer-360',
  path: '/customer-360',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customer-360': typeof Customer360Route
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/ops': typeof OpsRoute
  '/sql': typeof SqlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customer-360': typeof Customer360Route
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/ops': typeof OpsRoute
  '/sql': typeof SqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customer-360': typeof Customer360Route
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/ops': typeof OpsRoute
  '/sql': typeof SqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/customer-360'
    | '/jobs'
    | '/models'
    | '/ops'
    | '/sql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit' | '/customer-360' | '/jobs' | '/models' | '/ops' | '/sql'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/customer-360'
    | '/jobs'
    | '/models'
    | '/ops'
    | '/sql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  Customer360Route: typeof Customer360Route
  JobsRoute: typeof JobsRoute
  ModelsRoute: typeof ModelsRoute
  OpsRoute: typeof OpsRoute
  SqlRoute: typeof SqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-360': {
      id: '/customer-360'
      path: '/customer-360'
      fullPath: '/customer-360'
      preLoaderRoute: typeof Customer360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  Customer360Route: Customer360Route,
  JobsRoute: JobsRoute,
  ModelsRoute: ModelsRoute,
  OpsRoute: OpsRoute,
  SqlRoute: SqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
