/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BillingPortalRouteImport } from './routes/billing-portal'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevPersonasRouteImport } from './routes/dev.personas'
import { Route as DevEmailsRouteImport } from './routes/dev.emails'
import { Route as DevAssetsRouteImport } from './routes/dev.assets'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAccessibilityRouteImport } from './routes/_app/accessibility'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat.index'
import { Route as ShareMShareIdRouteImport } from './routes/share.m.$shareId'
import { Route as ShareCConversationIdRouteImport } from './routes/share.c.$conversationId'
import { Route as DevRenderAssetNameRouteImport } from './routes/dev.render-asset.$name'
import { Route as AppChatTrialRouteImport } from './routes/_app/chat.trial'
import { Route as AppChatIdRouteImport } from './routes/_app/chat.$id'

const BillingPortalRoute = BillingPortalRouteImport.update({
  id: '/billing-portal',
  path: '/billing-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPersonasRoute = DevPersonasRouteImport.update({
  id: '/dev/personas',
  path: '/dev/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEmailsRoute = DevEmailsRouteImport.update({
  id: '/dev/emails',
  path: '/dev/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAssetsRoute = DevAssetsRouteImport.update({
  id: '/dev/assets',
  path: '/dev/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessibilityRoute = AppAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const ShareMShareIdRoute = ShareMShareIdRouteImport.update({
  id: '/share/m/$shareId',
  path: '/share/m/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCConversationIdRoute = ShareCConversationIdRouteImport.update({
  id: '/share/c/$conversationId',
  path: '/share/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRenderAssetNameRoute = DevRenderAssetNameRouteImport.update({
  id: '/dev/render-asset/$name',
  path: '/dev/render-asset/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatTrialRoute = AppChatTrialRouteImport.update({
  id: '/chat/trial',
  path: '/chat/trial',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing-portal': typeof BillingPortalRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/billing': typeof AppBillingRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/dev/assets': typeof DevAssetsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/dev/personas': typeof DevPersonasRoute
  '/chat/$id': typeof AppChatIdRoute
  '/chat/trial': typeof AppChatTrialRoute
  '/dev/render-asset/$name': typeof DevRenderAssetNameRoute
  '/share/c/$conversationId': typeof ShareCConversationIdRoute
  '/share/m/$shareId': typeof ShareMShareIdRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing-portal': typeof BillingPortalRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/billing': typeof AppBillingRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/dev/assets': typeof DevAssetsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/dev/personas': typeof DevPersonasRoute
  '/chat/$id': typeof AppChatIdRoute
  '/chat/trial': typeof AppChatTrialRoute
  '/dev/render-asset/$name': typeof DevRenderAssetNameRoute
  '/share/c/$conversationId': typeof ShareCConversationIdRoute
  '/share/m/$shareId': typeof ShareMShareIdRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/billing-portal': typeof BillingPortalRoute
  '/_app/accessibility': typeof AppAccessibilityRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/dev/assets': typeof DevAssetsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/dev/personas': typeof DevPersonasRoute
  '/_app/chat/$id': typeof AppChatIdRoute
  '/_app/chat/trial': typeof AppChatTrialRoute
  '/dev/render-asset/$name': typeof DevRenderAssetNameRoute
  '/share/c/$conversationId': typeof ShareCConversationIdRoute
  '/share/m/$shareId': typeof ShareMShareIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing-portal'
    | '/accessibility'
    | '/billing'
    | '/settings'
    | '/usage'
    | '/login'
    | '/signup'
    | '/verify'
    | '/dev/assets'
    | '/dev/emails'
    | '/dev/personas'
    | '/chat/$id'
    | '/chat/trial'
    | '/dev/render-asset/$name'
    | '/share/c/$conversationId'
    | '/share/m/$shareId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing-portal'
    | '/accessibility'
    | '/billing'
    | '/settings'
    | '/usage'
    | '/login'
    | '/signup'
    | '/verify'
    | '/dev/assets'
    | '/dev/emails'
    | '/dev/personas'
    | '/chat/$id'
    | '/chat/trial'
    | '/dev/render-asset/$name'
    | '/share/c/$conversationId'
    | '/share/m/$shareId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/billing-portal'
    | '/_app/accessibility'
    | '/_app/billing'
    | '/_app/settings'
    | '/_app/usage'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/dev/assets'
    | '/dev/emails'
    | '/dev/personas'
    | '/_app/chat/$id'
    | '/_app/chat/trial'
    | '/dev/render-asset/$name'
    | '/share/c/$conversationId'
    | '/share/m/$shareId'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BillingPortalRoute: typeof BillingPortalRoute
  DevAssetsRoute: typeof DevAssetsRoute
  DevEmailsRoute: typeof DevEmailsRoute
  DevPersonasRoute: typeof DevPersonasRoute
  DevRenderAssetNameRoute: typeof DevRenderAssetNameRoute
  ShareCConversationIdRoute: typeof ShareCConversationIdRoute
  ShareMShareIdRoute: typeof ShareMShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/billing-portal': {
      id: '/billing-portal'
      path: '/billing-portal'
      fullPath: '/billing-portal'
      preLoaderRoute: typeof BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/personas': {
      id: '/dev/personas'
      path: '/dev/personas'
      fullPath: '/dev/personas'
      preLoaderRoute: typeof DevPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/emails': {
      id: '/dev/emails'
      path: '/dev/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof DevEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/assets': {
      id: '/dev/assets'
      path: '/dev/assets'
      fullPath: '/dev/assets'
      preLoaderRoute: typeof DevAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accessibility': {
      id: '/_app/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AppAccessibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/m/$shareId': {
      id: '/share/m/$shareId'
      path: '/share/m/$shareId'
      fullPath: '/share/m/$shareId'
      preLoaderRoute: typeof ShareMShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/c/$conversationId': {
      id: '/share/c/$conversationId'
      path: '/share/c/$conversationId'
      fullPath: '/share/c/$conversationId'
      preLoaderRoute: typeof ShareCConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/render-asset/$name': {
      id: '/dev/render-asset/$name'
      path: '/dev/render-asset/$name'
      fullPath: '/dev/render-asset/$name'
      preLoaderRoute: typeof DevRenderAssetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/trial': {
      id: '/_app/chat/trial'
      path: '/chat/trial'
      fullPath: '/chat/trial'
      preLoaderRoute: typeof AppChatTrialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccessibilityRoute: typeof AppAccessibilityRoute
  AppBillingRoute: typeof AppBillingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppChatTrialRoute: typeof AppChatTrialRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessibilityRoute: AppAccessibilityRoute,
  AppBillingRoute: AppBillingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppChatTrialRoute: AppChatTrialRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BillingPortalRoute: BillingPortalRoute,
  DevAssetsRoute: DevAssetsRoute,
  DevEmailsRoute: DevEmailsRoute,
  DevPersonasRoute: DevPersonasRoute,
  DevRenderAssetNameRoute: DevRenderAssetNameRoute,
  ShareCConversationIdRoute: ShareCConversationIdRoute,
  ShareMShareIdRoute: ShareMShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
