import { readFileSync, watch } from 'node:fs';
import { createServer, type ServerResponse } from 'node:http';
import path from 'node:path';
import { Marked } from 'marked';
import markedAlert from 'marked-alert';
import { markedHighlight } from 'marked-highlight';
import hljs from 'highlight.js';
import { isMainModule } from '../lib/is-main.js';

const ROOT = process.cwd();

/**
 * Resolve the preview port from the HB_README_PREVIEW_PORT env var.
 * This var is generated by scripts/generate-env.ts based on the current
 * worktree's port slot, ensuring different worktrees don't collide.
 */
export function resolvePort(): number {
  const raw = process.env['HB_README_PREVIEW_PORT'];
  if (!raw) {
    throw new Error(
      'HB_README_PREVIEW_PORT is not set. Run `pnpm generate:env` first, or invoke this script via `tsx scripts/with-env.ts`.'
    );
  }
  const port = Number(raw);
  if (!Number.isInteger(port) || port <= 0 || port > 65_535) {
    throw new Error(`HB_README_PREVIEW_PORT is invalid: "${raw}"`);
  }
  return port;
}
const CSS_PATH = path.resolve(ROOT, 'node_modules/github-markdown-css/github-markdown.css');

const MIME_TYPES: Record<string, string> = {
  svg: 'image/svg+xml',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  ico: 'image/x-icon',
  webp: 'image/webp',
};

const marked = new Marked(
  { gfm: true },
  markedAlert(),
  markedHighlight({
    langPrefix: 'hljs language-',
    highlight: (code, lang) => {
      if (lang && hljs.getLanguage(lang)) {
        return hljs.highlight(code, { language: lang }).value;
      }
      return hljs.highlightAuto(code).value;
    },
  })
);

/**
 * Check that a URL path does not escape the repo root via `..`.
 */
export function isSafePath(urlPath: string): boolean {
  return !urlPath.includes('..') && urlPath !== '/';
}

/**
 * Render a complete HTML document from a markdown string and GitHub CSS.
 */
export function renderPage(markdown: string, css: string): string {
  const parsed = marked.parse(markdown);
  /* v8 ignore next -- marked.parse is synchronous here, so it always returns a string */
  const body: string = typeof parsed === 'string' ? parsed : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>README preview</title>
  <style>${css}</style>
  <style>
    body { max-width: 1012px; margin: 0 auto; padding: 40px 44px; background: #fff; }
    @media (prefers-color-scheme: dark) { body { background: #0d1117; } }
    .markdown-body { box-sizing: border-box; }
  </style>
  <script>
    const source = new EventSource('/reload');
    source.addEventListener('message', () => { location.reload(); });
  </script>
</head>
<body class="markdown-body">${body}</body>
</html>`;
}

/**
 * Read the README and the CSS, render the page.
 */
function renderReadme(): string {
  const markdown = readFileSync(path.join(ROOT, 'README.md'), 'utf8');
  const css = readFileSync(CSS_PATH, 'utf8');
  return renderPage(markdown, css);
}

/**
 * Start the preview server on the given port. Returns the server instance.
 */
export function startServer(port: number): ReturnType<typeof createServer> {
  const clients = new Set<ServerResponse>();

  const server = createServer((req, res) => {
    /* v8 ignore next -- Node always sets req.url on an incoming request */
    const url = req.url ?? '/';

    // SSE endpoint for live reload
    if (url === '/reload') {
      res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        Connection: 'keep-alive',
      });
      clients.add(res);
      req.on('close', () => clients.delete(res));
      return;
    }

    // Serve static files (SVGs, images) from repo root
    if (isSafePath(url)) {
      try {
        const filePath = path.join(ROOT, decodeURIComponent(url));
        const content = readFileSync(filePath);
        /* v8 ignore next -- split always yields at least one element, so pop never returns undefined */
        const extension = filePath.split('.').pop()?.toLowerCase() ?? '';
        res.writeHead(200, {
          'Content-Type': MIME_TYPES[extension] ?? 'application/octet-stream',
        });
        res.end(content);
        return;
      } catch {
        // Fall through to render the README page
      }
    }

    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(renderReadme());
  });

  watch(path.join(ROOT, 'README.md'), () => {
    for (const client of clients) {
      client.write('data: reload\n\n');
    }
  });

  server.listen(port, () => {
    console.log(`README preview: http://localhost:${String(port)}`);
  });

  return server;
}

/* v8 ignore start -- CLI wiring; the server is covered via unit tests on an ephemeral port */
const isMain = isMainModule(import.meta.url);
if (isMain) startServer(resolvePort());
/* v8 ignore stop */
