DROP TABLE "account_deletion_events" CASCADE;--> statement-breakpoint
DROP TABLE "content_items" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_forks" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_members" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_spending" CASCADE;--> statement-breakpoint
DROP TABLE "conversations" CASCADE;--> statement-breakpoint
DROP TABLE "device_tokens" CASCADE;--> statement-breakpoint
DROP TABLE "epoch_members" CASCADE;--> statement-breakpoint
DROP TABLE "epochs" CASCADE;--> statement-breakpoint
DROP TABLE "ledger_entries" CASCADE;--> statement-breakpoint
DROP TABLE "llm_completions" CASCADE;--> statement-breakpoint
DROP TABLE "media_generations" CASCADE;--> statement-breakpoint
DROP TABLE "member_budgets" CASCADE;--> statement-breakpoint
DROP TABLE "messages" CASCADE;--> statement-breakpoint
DROP TABLE "payments" CASCADE;--> statement-breakpoint
DROP TABLE "projects" CASCADE;--> statement-breakpoint
DROP TABLE "service_evidence" CASCADE;--> statement-breakpoint
DROP TABLE "shared_links" CASCADE;--> statement-breakpoint
DROP TABLE "shared_messages" CASCADE;--> statement-breakpoint
DROP TABLE "usage_records" CASCADE;--> statement-breakpoint
DROP TABLE "users" CASCADE;--> statement-breakpoint
DROP TABLE "wallets" CASCADE;