import { TERMS_OF_SERVICE_EFFECTIVE_DATE, BILLING_CONTACT_EMAIL } from '../constants.js';
import { TOTAL_FEE_RATE, STORAGE_COST_PER_1K_CHARS } from '../affordability/constants.js';
import { FEE_CATEGORIES, formatFeePercent } from '../affordability/fees.js';
import type { LegalSection, LegalDocumentMeta } from './types.js';

export const TERMS_OF_SERVICE_META: LegalDocumentMeta = {
  title: 'Terms of Service',
  effectiveDate: TERMS_OF_SERVICE_EFFECTIVE_DATE,
  contactEmail: BILLING_CONTACT_EMAIL,
};

const totalFeePercent = formatFeePercent(TOTAL_FEE_RATE);
const feeBreakdownClause = FEE_CATEGORIES.map(
  (category) => `${formatFeePercent(category.rate)} ${category.label}`
).join(', ');
// Skip the breakdown bullet entirely when no fee category has a positive rate,
// to avoid rendering a malformed "Fee breakdown: ." sentence.
/* v8 ignore next -- @preserve defensive empty-arm: FEE_CATEGORIES is non-empty for every configuration with a positive fee rate; the `[]` arm guards an all-zero-rate config that does not currently exist */
const feeBreakdownBullets =
  FEE_CATEGORIES.length > 0 ? [`Fee breakdown: ${feeBreakdownClause}.`] : [];
const storageCostPer1k = `$${String(STORAGE_COST_PER_1K_CHARS)}`;

export const TERMS_SECTIONS: LegalSection[] = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    simplyPut: 'Using HushBox means you agree to these terms.',
    points: [
      'By creating a HushBox account or using the service, you agree to be bound by these Terms of Service.',
      'If you do not agree to these terms, do not use HushBox.',
      'Your continued use of the service constitutes ongoing acceptance.',
    ],
  },
  {
    id: 'description',
    title: 'Description of Service',
    simplyPut: 'One interface to chat with any AI model.',
    points: [
      'HushBox is an AI chat application that provides access to multiple AI models through a unified interface.',
      'Responses are generated by third-party AI providers. HushBox routes your requests and stores your conversations in encrypted form.',
      'HushBox is not a professional advisor, therapist, lawyer, or medical provider. The service is subject to availability.',
    ],
  },
  {
    id: 'account-responsibilities',
    title: 'Account Responsibilities',
    simplyPut: 'Keep your password safe. We can\u2019t recover it.',
    points: [
      'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.',
      'Your password is never stored on our servers. If you lose your password and your recovery phrase, your encrypted data cannot be recovered by anyone, including HushBox.',
      'You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.',
    ],
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use',
    simplyPut: 'Don\u2019t use HushBox for anything illegal or harmful.',
    points: [
      'You agree not to use HushBox to generate illegal content, extract harmful information, deceive or defraud others, or engage in any activity that violates applicable law.',
      'You agree not to reverse engineer, decompile, or disassemble any part of the service.',
      'Automated access or bot usage is not permitted without prior written permission from HushBox.',
      'We reserve the right to suspend or terminate accounts that violate this policy.',
    ],
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    simplyPut: 'Your inputs are yours. We\u2019ll never claim your AI outputs.',
    points: [
      'The HushBox application, brand, and source code are the property of LOME-AI LLC.',
      'Your inputs (messages you send) belong to you.',
      'HushBox will never claim ownership of any AI-generated output. You are free to use AI responses as you see fit.',
      'Note that AI-generated outputs may not be copyrightable under current law. This is an evolving area of law and is outside HushBox\u2019s control.',
    ],
  },
  {
    id: 'ai-disclaimer',
    title: 'AI Content Disclaimer',
    simplyPut: 'AI can be wrong. Don\u2019t bet your life on it.',
    points: [
      'AI-generated responses may be inaccurate, incomplete, biased, or entirely fabricated. You should independently verify any information received through the service.',
      'Do not rely on AI responses for medical, legal, financial, or safety-critical decisions.',
      'HushBox is not liable for any actions you take based on AI-generated content.',
    ],
  },
  {
    id: 'third-party-services',
    title: 'Third-Party Services',
    simplyPut: 'We depend on AI providers. Their availability affects ours.',
    points: [
      'HushBox relies on third-party AI providers to generate responses. The availability, quality, and behavior of these providers is outside our control.',
      'We are not responsible for changes to third-party provider policies, pricing, or service availability.',
      'Model availability may change without notice as providers update their offerings.',
    ],
  },
  {
    id: 'payment-terms',
    title: 'Payment Terms',
    simplyPut: `Pay for what you use. ${totalFeePercent} fee. No hidden charges.`,
    points: [
      `HushBox operates on a pay-as-you-go basis. A ${totalFeePercent} fee is applied to all AI model usage.`,
      ...feeBreakdownBullets,
      `A storage fee of ${storageCostPer1k} per 1,000 characters is charged for storing your conversations.`,
      'All purchases are final. If you believe a charge was made in error, contact billing@hushbox.ai within 30 days.',
    ],
  },
  {
    id: 'limitation-of-liability',
    title: 'Limitation of Liability',
    simplyPut: 'Our liability is capped at what you\u2019ve paid us.',
    points: [
      'To the maximum extent permitted by law, HushBox\u2019s total liability to you is limited to the fees you have paid to HushBox in the 12 months preceding the claim.',
      'HushBox is not liable for any indirect, incidental, consequential, special, or punitive damages.',
    ],
  },
  {
    id: 'warranties',
    title: 'Disclaimer of Warranties',
    simplyPut: 'The service is provided as-is.',
    points: [
      'HushBox is provided "as is" and "as available" without warranties of any kind, whether express or implied.',
      'We do not guarantee the accuracy, completeness, or reliability of AI-generated content, the availability or uninterrupted operation of the service, or fitness for any particular purpose.',
    ],
  },
  {
    id: 'termination',
    title: 'Termination',
    simplyPut:
      'You can leave anytime, including permanently deleting your account. We can terminate for violations.',
    points: [
      'You may delete your account at any time from your Settings page.',
      'You may stop using HushBox without deleting your account; we keep your encrypted data while your account exists.',
      'HushBox may suspend or terminate your account if you violate these Terms of Service.',
      'Upon termination by either side, certain provisions survive, including Limitation of Liability, Intellectual Property, Disclaimer of Warranties, and Governing Law.',
    ],
  },
  {
    id: 'governing-law',
    title: 'Governing Law',
    simplyPut: 'Indiana law applies.',
    points: [
      'These terms are governed by the laws of the State of Indiana, United States, without regard to conflict of law principles.',
      'Any disputes arising from these terms or your use of HushBox shall first be attempted to be resolved informally. If informal resolution fails, disputes shall be resolved in the state courts of Indiana.',
      'You agree to waive any right to participate in a class action lawsuit or class-wide arbitration against HushBox.',
    ],
  },
  {
    id: 'changes',
    title: 'Changes to Terms',
    simplyPut: 'Changes are effective when posted.',
    points: [
      'We may modify these Terms of Service at any time. Changes are effective when posted on this page.',
      'Your continued use of HushBox after changes are posted constitutes your acceptance of the updated terms.',
    ],
  },
];
