import s5Track from './05-props/s5.track.json' with { type: 'json' };
import type { AdSpecInput } from '../tools/remotion/index.js';

const FPS = 30;
const sec = (seconds: number): number => Math.round(seconds * FPS);

/** Asset paths are relative to the ads public dir (the ads root). */
const asset = (path: string): string => `2026-07-hq-tour/${path}`;

/**
 * "A Tour of HushBox HQ" — DATA ONLY; the <Ad> engine renders it. Scene and
 * overlay timing come from 01-brief/copy-deck.md. Scene 5 currently plays the
 * full-frame UI capture as a placeholder; the green-screen composite and the
 * trim-to-two-moments cut land in a later pass.
 */
export const hqTour: AdSpecInput = {
  id: 'hq-tour',
  width: 1080,
  height: 1920,
  fps: FPS,
  durationInFrames: sec(30),
  scenes: [
    {
      type: 'video',
      id: 's1-doors',
      from: sec(0),
      durationInFrames: sec(3),
      src: asset('02-ai-shots/s1-doors/s1-take1-seedance20.mp4'),
    },
    {
      type: 'video',
      id: 's2-ad-targeting',
      from: sec(3),
      durationInFrames: sec(5),
      src: asset('02-ai-shots/s2-ad-targeting/s2-take1-seedance20.mp4'),
    },
    {
      type: 'video',
      id: 's3-monetization',
      from: sec(8),
      durationInFrames: sec(5),
      src: asset('02-ai-shots/s3-monetization/s3-bakeoff-seedance20.mp4'),
    },
    {
      type: 'video',
      id: 's4-unbuilt',
      from: sec(13),
      durationInFrames: sec(5),
      src: asset('02-ai-shots/s4-unbuilt/s4-take1-seedance20.mp4'),
    },
    {
      // Push-in on the phone; the UI capture is keyed into its green screen.
      // `track` is generated by the seeded chroma tracker:
      //   tsx tools/remotion/generate-track.ts <plate> 540 1060 70 05-props/s5.track.json 30
      // NOTE: static-take1.webm is the pre-fix (grey) capture; the crisp demo
      // take stands in until a clean cursor-free static take is recaptured.
      type: 'screenReplace',
      id: 's5-phone',
      from: sec(18),
      durationInFrames: sec(4),
      plateSrc: asset('02-ai-shots/s5-only-room/s5-take1-seedance20.mp4'),
      screenSrc: asset('03-screen-capture/demo-take1.webm'),
      track: s5Track.frames,
    },
    {
      // Hard cut to the full-frame UI (the cursor take): the two key moments.
      type: 'video',
      id: 's5-ui',
      from: sec(22),
      durationInFrames: sec(4),
      src: asset('03-screen-capture/demo-take1.webm'),
      muted: true,
    },
    {
      type: 'receipt',
      id: 's6-receipt',
      from: sec(26),
      durationInFrames: sec(4),
      lines: [
        'A hundred models. One interface.',
        'Encrypted before we could ever read it.',
        'We take a cut of usage. That is the whole business.',
      ],
    },
  ],
  overlays: [
    { from: sec(0), durationInFrames: sec(3), text: 'Welcome to HushBox. Let us show you around.' },
    { from: sec(3), durationInFrames: sec(5), text: 'Ad targeting. No one works here.' },
    {
      from: sec(8),
      durationInFrames: sec(5),
      text: 'Data monetization. It is encrypted before it reaches us.',
    },
    {
      from: sec(13),
      durationInFrames: sec(5),
      text: 'The floor for reading your messages. Never built.',
    },
    { from: sec(18), durationInFrames: sec(4), text: 'We built one thing.' },
    { from: sec(26), durationInFrames: sec(4), text: 'A hundred models. One cut of usage.' },
  ],
  music: {
    src: asset('06-music/bed-sonilo-take1.m4a'),
    // Hard-cut to silence on the receipt card at 26s — the silence is the payoff.
    endAtFrame: sec(26),
    // Swell base→peak over the 2s leading into the S5 push-in at 18s.
    swellFromFrame: sec(16),
    swellFrames: sec(2),
  },
  voiceovers: [
    { from: sec(0), src: asset('04-voiceover/line1-take7-FINAL.flac') },
    { from: sec(3), src: asset('04-voiceover/line2-take1-FINAL.flac') },
    { from: sec(8), src: asset('04-voiceover/line3-take2-FINAL.flac') },
    { from: sec(13), src: asset('04-voiceover/line4-take1-FINAL.flac') },
    { from: sec(18), src: asset('04-voiceover/line5-take1-FINAL.flac') },
    { from: sec(26), src: asset('04-voiceover/line6-take1-FINAL.flac') },
  ],
};
