import {
  Camera,
  Code,
  Drama,
  FileText,
  Film,
  Image as ImageIcon,
  Lightbulb,
  MessageSquare,
  Mic,
  Music as MusicIcon,
  Palette,
  Speaker,
  Telescope,
  Trees,
  Video as VideoIcon,
  Waves,
  type LucideIcon,
} from 'lucide-react';
import type { LegacyModality } from '@hushbox/shared';

export interface PromptSuggestion {
  id: string;
  icon: LucideIcon;
  label: string;
  prompts: string[];
}

export const textSuggestions: PromptSuggestion[] = [
  {
    id: 'code',
    icon: Code,
    label: 'Help me write code',
    prompts: [
      'Write a TypeScript function that takes an array of user objects with name and email fields, filters out users without valid email addresses, and returns the remaining users sorted alphabetically by name.',
      'Create a React custom hook called useDebounce that accepts a value and delay in milliseconds, and returns a debounced version of that value that only updates after the specified delay.',
      'Build a Python script that reads a CSV file containing sales data with columns for date, product, and amount, calculates the total revenue per product category, and exports the results to a new CSV file.',
      'Write a SQL query that finds all customers who have placed more than 3 orders in the last 30 days, including their total spend and average order value.',
      'Create a JavaScript function that takes a nested object of any depth and flattens it into a single-level object with dot-notation keys.',
      'Build a REST API endpoint in Node.js with Express that accepts a POST request with user registration data, validates the email and password, and returns appropriate success or error responses.',
      'Write a bash script that monitors a directory for new files, compresses any files larger than 10MB, and moves the originals to an archive folder.',
      'Create a React component that displays a paginated table of products with sorting by name, price, and date columns, and a search filter that updates the results in real-time.',
      'Write a Python function that connects to a PostgreSQL database, retrieves all orders from the last week, and generates a summary report with daily totals.',
      'Build a TypeScript utility that validates form data against a schema, returns detailed error messages for each invalid field, and supports nested object validation.',
      'Create a CSS animation that makes an element pulse with a glow effect, fading between two colors smoothly with a 2-second duration.',
      'Write a GitHub Actions workflow that runs tests on pull requests, checks code formatting, and deploys to staging when merged to the main branch.',
    ],
  },
  {
    id: 'explain',
    icon: FileText,
    label: 'Explain a concept',
    prompts: [
      'Explain how vaccines work to protect against diseases, including how they train the immune system to recognize and fight specific pathogens.',
      'Explain why the sky is blue during the day and turns orange and red during sunset, including the science behind light scattering.',
      'Explain how compound interest works and why starting to save early makes such a big difference for retirement.',
      'Explain what causes inflation and how it affects the purchasing power of money over time.',
      'Explain how habits form in the brain and what science says about the most effective ways to build new habits or break bad ones.',
      'Explain the difference between introversion and extroversion, and why these personality traits affect how people recharge their energy.',
      'Explain how black holes form and what happens to matter and light that gets too close to one.',
      'Explain what causes climate change and the main factors contributing to global temperature increases.',
      'Explain how credit scores work, what factors affect them, and why they matter for loans and financial decisions.',
      'Explain the placebo effect and why it sometimes works even when people know they are taking a placebo.',
      'Explain how the stock market works, including what it means to buy shares in a company and how stock prices are determined.',
      'Explain the difference between deductive and inductive reasoning, with examples of how each type of logic is used in everyday life.',
    ],
  },
  {
    id: 'brainstorm',
    icon: Lightbulb,
    label: 'Brainstorm ideas',
    prompts: [
      'Give me 10 creative date night ideas for couples who want to do something different from dinner and a movie, with options for different budgets.',
      'Brainstorm 8 thoughtful gift ideas for someone who says they do not want anything and already has everything they need.',
      'Come up with 10 ways to organize a small closet to maximize space and make it easier to find clothes in the morning.',
      'Generate 12 ideas for a memorable 50th birthday party that celebrates the guest of honor without being too over-the-top.',
      'Brainstorm 10 healthy meal prep ideas for busy weeknights that take less than 30 minutes and use simple ingredients.',
      'Come up with 8 creative ways to make exercise more enjoyable for someone who finds traditional workouts boring.',
      'Generate 10 ideas for starting a side project or hobby that could eventually turn into extra income.',
      'Brainstorm 8 ways to make a small apartment feel more spacious and organized without spending much money.',
      'Come up with 10 conversation starters for networking events that go beyond asking what someone does for work.',
      'Generate 12 ideas for family activities on a rainy weekend that do not involve screens and work for kids of different ages.',
      'Brainstorm 8 ways to reduce household expenses by $200-300 per month without drastically changing your lifestyle.',
      'Come up with 10 ideas for making long car trips more enjoyable for the whole family, including games and activities.',
    ],
  },
  {
    id: 'question',
    icon: MessageSquare,
    label: 'Answer a question',
    prompts: [
      'What is the best way to start learning a new language as an adult, and how long does it typically take to become conversational?',
      'What should I look for when buying a used car, and what are the red flags that indicate I should walk away?',
      'What are the most important things to know before buying a first home, including hidden costs that first-time buyers often overlook?',
      'What is the difference between a Roth IRA and a traditional IRA, and which one makes more sense for someone in their 30s?',
      'What are some effective strategies for dealing with work stress and preventing burnout while maintaining productivity?',
      'What should I consider when choosing between renting and buying a home in the current market?',
      'What are the key things to know about starting a small business, including the most common mistakes new entrepreneurs make?',
      'What is the best approach for having a difficult conversation with a family member about a sensitive topic?',
      'What should I pack for a two-week trip to Europe if I want to travel light with just a carry-on bag?',
      'What are the signs that it might be time to look for a new job, and how should I approach a job search while still employed?',
      'What are the pros and cons of different types of exercise like running, weightlifting, and yoga for overall health?',
      'What should I know about caring for aging parents, including resources available and how to have conversations about their future needs?',
    ],
  },
];

export const imageSuggestions: PromptSuggestion[] = [
  {
    id: 'image-scene',
    icon: ImageIcon,
    label: 'Render a scene',
    prompts: [
      'A neon-lit cyberpunk alley at dusk, rain reflecting signs, anamorphic lens flare',
      'Cozy bookshop interior in autumn, warm lamp lighting, dust motes in window beams',
      'Aerial drone shot of coastal cliffs at golden hour, long shadows on the sand',
      'Misty pine forest at dawn, sun rays cutting through fog, hyper-detailed moss on the rocks',
      'Crowded Tokyo crossing under heavy rain, reflections on wet asphalt, blade-runner palette',
      'Quiet Parisian cafe corner with a single croissant on a marble table, morning light',
      'Snowy Swiss village street at night, lit windows, gentle snowfall, painterly mood',
      'Sunlit Mediterranean rooftop with terracotta tiles and a single olive tree, midday',
      'Abandoned greenhouse overtaken by ferns and orchids, soft diffused light through cracked glass',
      'Desert highway at sunset, lone diner with a flickering neon sign, wide cinematic frame',
      'Underground subway station at 3am, fluorescent lights, single waiting passenger, lonely mood',
      'Mountain lake at twilight with bioluminescent algae glowing along the shore',
    ],
  },
  {
    id: 'image-portrait',
    icon: Camera,
    label: 'Capture a portrait',
    prompts: [
      'Editorial portrait of an elderly fisherman, weathered face, soft window light, 85mm lens',
      'Studio portrait of a ballerina mid-pose, dramatic side lighting, dust in the air',
      'Candid black-and-white shot of a jazz pianist mid-performance, smoke and stage light',
      'Renaissance oil painting of a scholar at a writing desk, candlelight, deep chiaroscuro',
      'Cinematic close-up of an astronaut removing their helmet after landing, sweat and relief',
      'High-fashion portrait of a model in metallic couture against a saturated red backdrop',
      'Soft-focus portrait of a child holding a firefly in cupped hands, summer evening',
      'Black-and-white documentary portrait of a blacksmith at work, sparks frozen in time',
      'Environmental portrait of a chef in their kitchen, copper pots gleaming behind them',
      'Vintage 1970s polaroid of two siblings on a porch swing, faded colors and grain',
      'Cyberpunk portrait of a hacker lit only by their multi-monitor rig, magenta and cyan',
      'Renaissance fresco-style depiction of a modern programmer at a laptop, gilded details',
    ],
  },
  {
    id: 'image-art',
    icon: Palette,
    label: 'Stylized art',
    prompts: [
      'Watercolor botanical illustration of wildflowers in a sunlit meadow, soft washes',
      'Isometric pixel art of a tiny floating island with a waterfall and a single house',
      'Studio Ghibli style hillside village at golden hour, hand-painted clouds',
      'Art Nouveau poster of a sea goddess surrounded by waves and ornate floral borders',
      'Ukiyo-e woodblock print of a thunderstorm over Mt Fuji, deep indigo gradients',
      'Low-poly geometric landscape of mountains and a lake at sunset, flat-shaded',
      'Pen-and-ink sketch of an old library interior, hatching, intricate architectural detail',
      'Vaporwave 80s aesthetic poster with palm trees, grid floor, and a setting sun',
      'Charcoal drawing of a galloping horse in motion, smudged background, dramatic gesture',
      'Mosaic-style illustration of a phoenix rising, gold leaf accents on dark tile',
      'Surrealist Dali-inspired painting of melting clocks draped over a chess board',
      "Children's storybook illustration of a friendly dragon reading a book in a cave",
    ],
  },
  {
    id: 'image-concept',
    icon: Telescope,
    label: 'Concept design',
    prompts: [
      'Concept art for a futuristic biotech laboratory floating above a coral reef',
      'Sci-fi cargo ship cockpit interior, bioluminescent UI panels, crew of three visible',
      'Fantasy character concept of a desert nomad shaman with a staff of carved bone',
      'Industrial design render of a sleek electric motorcycle, studio lighting on white seamless',
      'Concept art for an underwater city with kelp-forest skyscrapers and submarine taxis',
      'Architectural concept for a library carved into the side of a mountain cliff',
      'Vehicle concept of a six-legged mech walker traversing an alien glacier',
      'Creature design of a deep-sea predator with bioluminescent stripes and feathered fins',
      'Costume concept for a courtly mage in a baroque sci-fi universe, brass and velvet',
      'Environment concept of a Martian colony greenhouse at sunset, low gravity dust',
      'Product render of a transparent acoustic guitar with internal LED accents',
      'Concept art of a clockwork forest where the trees have brass gears for branches',
    ],
  },
];

export const videoSuggestions: PromptSuggestion[] = [
  {
    id: 'video-cinematic',
    icon: VideoIcon,
    label: 'Cinematic shot',
    prompts: [
      'Slow dolly-in on a lone astronaut standing on a red Martian dune, sun behind them',
      'Tracking shot through a rainforest canopy, parting leaves to reveal a hidden waterfall',
      'Crane shot rising over a medieval battlefield at dawn, mist clearing to reveal armies',
      'Aerial drone shot of waves crashing on a coastline at sunset, golden hour palette',
      'Steady-cam walk through a bustling night market, neon signs reflecting in puddles',
      'Push-in close-up on a clock face as the second hand ticks past midnight, sharp focus',
      'Wide cinematic shot of a single car driving a desert highway, no other vehicles in sight',
      'Crane up from a chess board to reveal two grandmasters lit by a single overhead lamp',
      'Tracking shot through an abandoned cathedral, light streaming through stained glass',
      'Drone shot following a herd of horses galloping across a snowy plain at sunrise',
      'Steadicam follow of a chef walking through their bustling open kitchen during dinner rush',
      'Wide establishing shot of a futuristic city skyline at dusk, flying vehicles weaving between towers',
    ],
  },
  {
    id: 'video-slowmo',
    icon: Film,
    label: 'Slow motion',
    prompts: [
      'Slow-motion coffee pouring into a glass mug, steam rising, cinematic close-up',
      'A paper airplane gliding through a sunlit office in slow motion, dust motes in the air',
      'Hummingbird hovering by a flower, ultra-slow motion, wings frozen mid-beat',
      'Ink dropping into clear water in slow motion, swirling tendrils against black background',
      'Glass shattering against concrete in extreme slow motion, dramatic side lighting',
      'Slow-motion close-up of a match being struck, sulphur flame blooming into life',
      'Water balloon bursting in slow motion against bright sunlight, droplets like glass beads',
      'A diver entering a pool in slow motion, surface deformation and air bubbles trailing behind',
      'Slow-motion close-up of a champagne cork popping, foam erupting from the bottle neck',
      'A leaf falling in slow motion through autumn forest light, gentle rotation as it descends',
      'High-speed slow motion of a popcorn kernel exploding in a hot pan, butter splattering',
      'Slow-motion close-up of a dart piercing a balloon, latex peeling back like water',
    ],
  },
  {
    id: 'video-nature',
    icon: Trees,
    label: 'Nature footage',
    prompts: [
      'Timelapse of a flower blooming, cinematic close-up, soft natural backlight',
      'Aurora borealis dancing over a pine forest, time-lapse, stars trailing overhead',
      'Underwater shot of a coral reef bustling with tropical fish, sun rays piercing the surface',
      'Eagle soaring above a mountain range, camera tracking alongside in wide formation',
      'Time-lapse of storm clouds rolling over a wheat field, lightning forking on the horizon',
      'Macro footage of a honeybee collecting pollen from a sunflower, golden hour light',
      'Slow-motion shot of a wolf pack running through a snowy forest, breath visible in cold air',
      'Long lens shot of a humpback whale breaching the ocean surface, droplets cascading',
      'Time-lapse of seasons changing on a single maple tree, summer to winter',
      'Drone shot of a river winding through autumn forests, foliage in full color',
      'Macro footage of dewdrops forming on a spider web at sunrise, refracted light',
      'Wide shot of a meteor shower streaking across a desert night sky, no light pollution',
    ],
  },
  {
    id: 'video-motion',
    icon: Drama,
    label: 'Dynamic motion',
    prompts: [
      'Parkour athlete vaulting through a sunlit urban rooftop, handheld camera follows behind',
      'Skateboarder grinding a rail in a graffiti-covered skatepark, gopro chest mount',
      'Surfer carving through a barrel wave, water spraying off the board, slow shutter',
      'Motorcyclist leaning into a hairpin turn on a mountain pass, sparks from foot peg',
      'Dancer performing a contemporary solo on a rain-slicked stage under a single spotlight',
      'Drift car kicking up tire smoke around a hairpin, low-angle tracking shot',
      'Climber chalking up before reaching the crux of a granite face, long lens',
      'Capoeira pair sparring at sunset on a Brazilian beach, silhouettes against orange sky',
      'Snowboarder catching air off a fresh-powder kicker, white spray exploding behind them',
      'BMX rider hitting a tabletop in a sun-baked dirt park, dust trailing in the air',
      'Slackliner walking a high line between two cliff towers, valley far below in soft focus',
      'Free diver descending into deep blue water with a single breath, bubbles trailing up',
    ],
  },
];

export const audioSuggestions: PromptSuggestion[] = [
  {
    id: 'audio-music',
    icon: MusicIcon,
    label: 'Music track',
    prompts: [
      'Lo-fi hip-hop beat with vinyl crackle, mellow piano loop, 80 bpm',
      'Cinematic orchestral piece building to a heroic climax, brass and timpani lead',
      'Upbeat electronic dance track with a punchy synth lead and side-chained bass',
      'Solo acoustic guitar piece in the style of a contemplative folk ballad, fingerpicked',
      'Jazz trio improvisation: walking upright bass, brushed snare, soft tenor sax melody',
      'Minimalist piano piece in the style of Erik Satie, slow and reflective, sustained notes',
      'High-energy rock anthem with distorted guitars, four-on-the-floor drums, big chorus',
      'Synthwave instrumental with arpeggiated leads and gated reverb drums, 110 bpm',
      'Reggae groove with off-beat guitar chops, deep bassline, and warm horns',
      'Baroque-style harpsichord fugue in three voices, brisk tempo, contrapuntal',
      'Latin bossa nova with nylon guitar, soft brushed drums, and a flute melody',
      'Tribal percussion ensemble building from sparse to full polyrhythmic groove',
    ],
  },
  {
    id: 'audio-ambient',
    icon: Waves,
    label: 'Ambient soundscape',
    prompts: [
      'Forest ambience: birdsong, rustling leaves, distant stream, gentle wind in pines',
      'Coastal soundscape: waves on a pebble beach, gulls calling, ship bells in the distance',
      'Heavy thunderstorm rolling across a city, rain on a tin roof, occasional thunderclap',
      'Crackling fireplace in a quiet cabin, occasional log shift, soft howling wind outside',
      'Underwater ambience near a coral reef, muffled bubbles and distant whale song',
      'Late-night city sounds: distant traffic, occasional siren, a far-off train horn',
      'Dense tropical jungle at dawn, insect chorus building, parrots calling overhead',
      'Quiet library ambience: page turns, distant footsteps, faint pencil scratching',
      'Train compartment in motion: rhythmic clack of rails, gentle creak of carriage',
      'Snowstorm wind blowing past a wooden cabin, occasional gust rattling the windows',
      'Coffee shop ambience: espresso machine hisses, muted chatter, occasional cup clink',
      'Desert night ambience: cool wind, distant coyote calls, faint crackle of dying campfire',
    ],
  },
  {
    id: 'audio-voice',
    icon: Mic,
    label: 'Voice over',
    prompts: [
      'Calm female narration explaining quantum entanglement, conversational pacing',
      'Confident male voice-over for a tech product launch, energetic and modern',
      'Warm grandmotherly voice reading a bedtime story aloud, gentle pacing and pauses',
      'Authoritative documentary narrator describing the formation of galaxies, deliberate cadence',
      'Smooth radio DJ voice introducing the next track on a late-night jazz station',
      'Excited sports commentator calling the final seconds of a championship game',
      'Soothing meditation guide leading a body-scan relaxation, slow and breathy',
      'Gritty noir detective monologue describing a rain-soaked city at night',
      "Cheerful kids show host introducing the day's craft project, animated and warm",
      'Stern courtroom voice delivering closing arguments, measured and emphatic',
      'British nature documentary narrator describing a chase across the savanna',
      'Friendly podcast co-host welcoming listeners to a new episode about urban gardening',
    ],
  },
  {
    id: 'audio-sfx',
    icon: Speaker,
    label: 'Sound effects',
    prompts: [
      'Heavy wooden door creaking open in an old castle, faint echoing footsteps inside',
      'Sword unsheathing in a swift motion, metallic ring, then thud as it lands on a stone floor',
      'Sci-fi spaceship engine powering up: low rumble building into a high-frequency whine',
      'Glass bottle shattering on tile, followed by silence and a single small clink',
      'Electric crackle of a Tesla coil discharging, ozone-charged buzz, then sharp snap',
      'Bow string released and arrow whistling through the air, ending with a thunk into wood',
      'Vintage typewriter clatter: rapid key presses, carriage return ding, paper feed',
      'Old film projector running: rhythmic mechanical clicks and faint motor hum',
      'Magic spell charging up, ascending shimmer effect, then a sharp release whoosh',
      'Heavy metal gate slamming shut, chains rattling, padlock clicking into place',
      'Submarine sonar ping echoing through deep water, slow tail-out',
      'Old steam locomotive arriving at a station: hissing brakes, bell ringing, whistle blowing',
    ],
  },
];

export function getSuggestionsForModality(modality?: LegacyModality): PromptSuggestion[] {
  if (modality === 'image') return imageSuggestions;
  if (modality === 'video') return videoSuggestions;
  if (modality === 'audio') return audioSuggestions;
  return textSuggestions;
}
